datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://tfbi-prometheus-server
        isDefault: true
        jsonData:
          graphiteVersion: "1.1"
          tlsAuth: false
          tlsAuthWithCACert: false
          timeInterval: 10m
          timeout: 8m
          editable: true
          version: 1

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboardsConfigMaps:
  default: tfbi-grafana-dashboard-config

        

grafana.ini:
  server:
    protocol: https
    cert_file: /etc/grafana/certs/tls.crt
    cert_key: /etc/grafana/certs/tls.key
  auth.anonymous:
    enabled: true
    org_role: Admin

persistence:
  enabled: true

# Internal Load Balancer. Only clients located in the same VPC or a network connectecd to the VPC
# can access grafana. https://cloud.google.com/kubernetes-engine/docs/concepts/service-load-balancer
service:
  type: LoadBalancer
  port: 443
  targetPort: 3000
  annotations:
    cloud.google.com/load-balancer-type: "Internal"

# ## This publically exposes grafana to the internet. Only used for testing.
# service:
#   type: LoadBalancer
#   port: 80

extraSecretMounts:
  - name: grafana-tls
    mountPath: /etc/grafana/certs
    secretName: grafana-tls
    readOnly: true

readinessProbe:
  httpGet:
    path: /
    port: 3000
    scheme: HTTPS

livenessProbe:
  httpGet:
    path: /
    port: 3000
    scheme: HTTPS