{
 "title": "Terraform Cloud Business Insights (TFBI)",
 "description": "Terraform Cloud Business Insights (TFBI)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "organizations", "label": "organization", "query": "tf_organizations_info" },
   { "name": "project", "label": "project", "query": "tf_workspaces_info" }
  ]
 },
 "panels": [
  {
   "title": "Terraform Cloud Business Insights",
   "type": "text",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "# Terraform Cloud Business Insights\n\n![img](https://www.datocms-assets.com/2885/1620073844-blog-library-product-terraform-cloud-tfc-black-gradient.jpg)"
   }
  },
  {
   "title": "Organization Name",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tf_organizations_info{}[$__interval]"
    }
   ]
  },
  {
   "title": "SAML Enabled ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tf_organizations_info{}[$__interval]"
    }
   ]
  },
  {
   "title": "Assessment Enforced",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tf_organizations_info{}[$__interval]"
    }
   ]
  },
  {
   "title": "2FA Enforced",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tf_organizations_info{}[$__interval]"
    }
   ]
  },
  {
   "title": "Organization Count",
   "type": "stat",
   "description": "Total number of organizations.",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum_over_time(tf_organizations_info{name=~\"$organizations\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Teams Count",
   "type": "stat",
   "description": "Total number of Teams",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time(tf_teams_info{}[$__interval])"
    }
   ]
  },
  {
   "title": "Users count",
   "type": "stat",
   "description": "Total number of Users",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time(tf_teams_info[$__interval])"
    }
   ]
  },
  {
   "title": " Workspace Count",
   "type": "stat",
   "description": "Total number of workspaces.",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "tf_workspaces_info{organization=~\"$organizations\"}[$__interval]"
    }
   ]
  },
  {
   "title": "Number of Runs",
   "type": "stat",
   "description": "Number of Runs",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "tf_workspaces_info{organization=~\"$organizations\"}[$__interval]"
    }
   ]
  },
  {
   "title": "Teams Summary",
   "type": "table",
   "description": "Team Summary",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 10 },
   "targets": [
    { "expr": "tf_teams_info{}[$__interval]" }
   ]
  },
  {
   "title": "Total Organization Resources ",
   "type": "stat",
   "description": "All Resources Created by Terraform ( not just RUM)",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "tf_workspaces_info{organization=~\"$organizations\"}[$__interval]"
    }
   ]
  },
  {
   "title": "Successful Runs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 5, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "tf_workspaces_info{organization=~\"$organizations\",project =~\"$project\"}[$__interval]"
    }
   ]
  },
  {
   "title": "Total Run Failures",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 9, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "tf_workspaces_info{organization=~\"$organizations\",project =~\"$project\"}[$__interval]"
    }
   ]
  },
  {
   "title": "Drift Detection & Continuous Validation Enabled",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(assessments_enabled) (\n  sum_over_time(tf_workspaces_info{organization=~\"$organizations\", project=~\"$project\"}[$__interval])\n)",
     "legendFormat": "{{current_run_status}}"
    }
   ]
  },
  {
   "title": "Terraform Version Distribution",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(terraform_version) (\n  sum_over_time(tf_workspaces_info{organization=~\"$organizations\", project=~\"$project\"}[$__interval])\n)",
     "legendFormat": "{{current_run_status}}"
    }
   ]
  },
  {
   "title": "Workspace Status Overview",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(current_run_status) (\n  sum_over_time(tf_workspaces_info{organization=~\"$organizations\", project=~\"$project\"}[$__interval])\n)",
     "legendFormat": "{{current_run_status}}"
    }
   ]
  },
  {
   "title": "Workspace Summary",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "tf_workspaces_info{organization=~\"$organizations\",project =~\"$project\"}[$__interval]"
    }
   ]
  },
  {
   "title": "Workspace Count Over Time",
   "type": "timeseries",
   "description": "Workspace Count Over Time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count_over_time(tf_workspaces_info{organization=~\"$organizations\", project=~\"$project\"}[$__interval])",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "Workspace Status History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(current_run_status) (\n  sum_over_time(tf_workspaces_info{organization=~\"$organizations\", project=~\"$project\"}[$__interval])\n)",
     "legendFormat": "{{current_run_status}}"
    }
   ]
  },
  {
   "title": "Current Total Resources Under Management (RUM)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "tf_workspaces_info{organization=~\"$organizations\",project =~\"$project\"}[$__interval]"
    }
   ]
  },
  {
   "title": "Workspace RUM Breakdown (w/ 90% Threshold)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tf_workspaces_info{organization=~\"$organizations\",project =~\"$project\",rum_count!=\"0\"}[$__interval]",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Workspace RUM Breakdown",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "tf_workspaces_info{organization=~\"$organizations\",project =~\"$project\",rum_count!=\"0\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Project RUM Breakdown",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tf_workspaces_info{organization=~\"$organizations\",project =~\"$project\", rum_count!=\"0\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Registry Modules Count",
   "type": "stat",
   "description": "Total number of Registry Modules",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum_over_time(tf_registrymodules_info{organization=\"$organizations\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Registry Modules - No Code Distribution",
   "type": "piechart",
   "description": "Registry Modules - No Code Distribution",
   "gridPos": { "h": 10, "w": 7, "x": 5, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(no_code) (\n  count_over_time(tf_registrymodules_info{organization=\"$organizations\"}[$__interval])\n)"
    }
   ]
  },
  {
   "title": "Registry Modules - Provider Distribution",
   "type": "piechart",
   "description": "Registry Modules - Provider Distribution",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(provider) (\n  count_over_time(tf_registrymodules_info{organization=\"$organizations\"}[$__interval])\n)"
    }
   ]
  },
  {
   "title": "Registry Modules Summary",
   "type": "table",
   "description": "Registry Modules Summary",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "tf_registrymodules_info{organization=\"$organizations\"}[$__interval]"
    }
   ]
  },
  {
   "title": "Projects Count",
   "type": "stat",
   "description": "Total number of Projects",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 106 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum_over_time(tf_projects_info{organization=\"$organizations\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Project Count Over Time",
   "type": "timeseries",
   "description": "Project Count Over Time",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count_over_time(tf_projects_info{organization=\"$organizations\"}[$__interval])",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "Projects Summary",
   "type": "table",
   "description": "Summary of Projects",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "tf_projects_info{organization=\"$organizations\"}[$__interval]"
    }
   ]
  },
  {
   "title": "Policy Set Count",
   "type": "stat",
   "description": "Total number of policy sets",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 122 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum_over_time(tf_policysets_info{organization=\"$organizations\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Total Policy Check Failures",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 5, "y": 122 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "tf_workspaces_info{organization=\"$organizations\"}[$__interval]"
    }
   ]
  },
  {
   "title": "Policy Type Distribution",
   "type": "piechart",
   "description": "Policy Type Distribution",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 122 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(kind) (tf_policysets_info{organization=\"$organizations\"}) "
    }
   ]
  },
  {
   "title": "Policy Set Summary",
   "type": "table",
   "description": "Policy Set Summary",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 132 },
   "targets": [
    {
     "expr": "tf_policysets_info{organization=\"$organizations\"} [$__interval]"
    }
   ]
  },
  {
   "title": "Exporter Status",
   "type": "stat",
   "description": "Result of last API scrape attempt.",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 143 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tf_exporter_last_scrape_error[$__interval]"
    }
   ]
  },
  {
   "title": "Exporter Duration Stats",
   "type": "timeseries",
   "description": "Time taken by each individual scraper.",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " last_over_time(tf_exporter_collector_duration_seconds[$__interval])",
     "legendFormat": "{{collector}}"
    }
   ]
  }
 ]
}